runtime: nodejs18

handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html

env_variables:
  REACT_APP_BASE_URL: "https://parktime-frontend-tyler-poff.uk.r.appspot.com"
  REACT_APP_API_BASE_URL: "https://parktime-backend-tyler-poff.uk.r.appspot.com/"
  # REACT_APP_GOOGLE_CLIENT_ID: "1063978570955-u9lhuv9kpdlvd510huag8att3ki7nn41.apps.googleusercontent.com"
  # REACT_APP_GOOGLE_CLIENT_SECRET: "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"